use soroban_sdk::{testutils::Events, xdr, Address, Env, Event, TryFromVal, Val, Vec};

/// Decodes a raw emitted contract event (XDR) into `(topics, data)`.
///
/// Soroban testutils exposes events as [`ContractEvents`](soroban_sdk::testutils::ContractEvents),
/// which internally stores XDR [`ContractEvent`](soroban_sdk::xdr::ContractEvent) values.
/// This helper converts the XDR topics/data into `soroban_sdk::Val` so tests can inspect
/// topics and data using normal Soroban conversions (`TryFromVal` / `IntoVal`).
///
/// Returns `None` if any topic or the data payload can't be converted into `Val` for the
/// provided `Env`.
///
/// # Example
/// ```ignore
/// let events = env.events().all().filter_by_contract(&contract);
/// for ev in events.events().iter() {
///     let (topics, data) = utils::testing_utils::decode_event_topics_data(&env, ev).unwrap();
///     // ... inspect topics/data ...
/// }
/// ```
pub fn decode_event_topics_data(env: &Env, event: &xdr::ContractEvent) -> Option<(Vec<Val>, Val)> {
    // In the current Soroban SDK version this enum has a single variant (`V0`),
    // so this destructure is infallible.
    let xdr::ContractEventBody::V0(v0) = &event.body;

    let mut topics = Vec::<Val>::new(env);
    for t in v0.topics.iter() {
        topics.push_back(Val::try_from_val(env, t).ok()?);
    }
    let data = Val::try_from_val(env, &v0.data).ok()?;
    Some((topics, data))
}

/// Asserts that the environment emitted exactly one event: `expected`.
///
/// This is a **strict equality** assertion over `env.events().all()`:
/// the full event list must be exactly `[expected]` (no extra events).
///
/// Uses the event struct's `.topics()` and `.data()` methods (generated by `#[contractevent]`)
/// to compare against emitted events. No more hardcoding topic names or field keys!
///
/// # Example
/// ```ignore
/// use crate::events::OwnershipTransferred;
///
/// let expected = OwnershipTransferred {
///     previous_owner: owner.clone(),
///     new_owner: new_owner.clone(),
/// };
/// assert_eq_event(&env, &contract, expected);
/// ```
pub fn assert_eq_event<E: Event>(env: &Env, contract: &Address, expected: E) {
    // Compare against the emitted `xdr::ContractEvent` directly. This avoids the
    // `xdr -> Val` roundtrip and ensures we match exactly what was emitted.
    //
    // IMPORTANT: This asserts *equality* (not "contains").
    extern crate std;

    assert_eq!(
        env.events().all(),
        std::vec![expected.to_xdr(env, contract)],
        "Expected exactly one event. Expected topics: {:?}, data: {:?}",
        expected.topics(env),
        expected.data(env),
    );
}

/// Asserts that the contract emitted an event equal to `expected`.
///
/// This is a **contains** assertion: after filtering events by `contract`,
/// `expected` must appear at least once (order doesn't matter; extra events allowed).
///
/// Uses the event struct's `.topics()` and `.data()` methods (generated by `#[contractevent]`)
/// to compare against emitted events. No more hardcoding topic names or field keys!
///
/// # Example
/// ```ignore
/// use crate::events::OwnershipTransferred;
///
/// let expected = OwnershipTransferred {
///     previous_owner: owner.clone(),
///     new_owner: new_owner.clone(),
/// };
/// assert_eq_event(&env, &contract, expected);
/// ```
pub fn assert_contains_event<E: Event>(env: &Env, contract: &Address, expected: E) {
    // Compare against the emitted `xdr::ContractEvent` directly. This avoids the
    // `xdr -> Val` roundtrip and ensures we match exactly what was emitted.
    let expected_xdr = expected.to_xdr(env, contract);

    let events = env.events().all().filter_by_contract(contract);
    let mut found = false;
    for event in events.events().iter() {
        if *event == expected_xdr {
            found = true;
            break;
        }
    }

    assert!(
        found,
        "Expected event not found. Expected topics: {:?}, data: {:?}",
        expected.topics(env),
        expected.data(env)
    );
}

/// Asserts that the environment emitted events that match `expected_events` exactly.
///
/// This is a **strict equality** assertion over `env.events().all()`:
/// the full event list must match `expected_events` **in order** and **count**
/// (no missing/extra events).
///
/// # Example
/// ```ignore
/// assert_eq_events(env, &contract, &[
///     &Event1 { ... },
///     &Event2 { ... },
/// ]);
/// ```
pub fn assert_eq_events(env: &Env, contract: &Address, expected_events: &[&dyn Event]) {
    // Note: this module is only compiled for tests / testutils usage, where `std` is available.
    extern crate std;
    let expected_xdrs: std::vec::Vec<xdr::ContractEvent> =
        expected_events.iter().map(|e| e.to_xdr(env, contract)).collect();

    assert_eq!(env.events().all(), expected_xdrs, "Expected events to match exactly");
}

/// Asserts that all `expected_events` were emitted by the contract (in any order).
///
/// This is a **contains** assertion with multiset semantics: after filtering events by
/// `contract`, every expected event must be present, and duplicates in `expected_events`
/// require duplicate emissions. Extra emitted events are allowed.
///
/// # Example
/// ```ignore
/// assert_eq_events(env, &contract, &[
///     &Event1 { ... },
///     &Event2 { ... },
/// ]);
/// ```
pub fn assert_contains_events(env: &Env, contract: &Address, expected_events: &[&dyn Event]) {
    // Note: this module is only compiled for tests / testutils usage, where `std` is available.
    extern crate std;
    let events = env.events().all().filter_by_contract(contract);
    let raw_events = events.events();
    // Track which emitted events have already been matched so that duplicate expectations
    // require duplicate emissions (multiset semantics).
    // We use a `std::vec::Vec<bool>` as a "used" mask to implement multiset matching.
    let mut used: std::vec::Vec<bool> = std::vec![false; raw_events.len()];

    for (i, expected) in expected_events.iter().enumerate() {
        let expected_xdr = expected.to_xdr(env, contract);

        let mut found = false;
        for (idx, event) in raw_events.iter().enumerate() {
            if used[idx] {
                continue;
            }
            if *event == expected_xdr {
                used[idx] = true;
                found = true;
                break;
            }
        }

        assert!(
            found,
            "Expected event #{} not found. Expected topics: {:?}, data: {:?}",
            i,
            expected.topics(env),
            expected.data(env)
        );
    }
}
