[workspace]
resolver = "2"
members = [ "endpoint-v2", "upgrader", "layerzero-views", "message-libs/*", "workers/*" ]
exclude = [ "dependencies" ]

[workspace.package]
edition = "2021"
version = "0.0.1"

[workspace.dependencies]
sha3 = "0.10"
ed25519-dalek = "2"
hex-literal = "1.0.0"
k256 = "0.13"
rand = "0.8"

[workspace.dependencies.soroban-sdk]
version = "25.1.1"
features = [ "hazmat-address", "hazmat-crypto" ]

[workspace.dependencies.cfg-if]
version = "1.0"
default-features = false

[workspace.dependencies.common-macros]
path = "../common-utils-macros-stellar-contracts"

[workspace.dependencies.dvn]
path = "workers/dvn"

[workspace.dependencies.dvn-fee-lib]
path = "workers/dvn-fee-lib"

[workspace.dependencies.endpoint-v2]
path = "endpoint-v2"
default-features = false

[workspace.dependencies.executor]
path = "workers/executor"

[workspace.dependencies.executor-fee-lib]
path = "workers/executor-fee-lib"

[workspace.dependencies.fee-lib-interfaces]
path = "workers/fee-lib-interfaces"

[workspace.dependencies.message-lib-common]
path = "message-libs/message-lib-common"

[workspace.dependencies.simple-message-lib]
path = "message-libs/simple-message-lib"

[workspace.dependencies.uln302]
path = "message-libs/uln-302"
default-features = false

[workspace.dependencies.utils]
path = "../common-utils-stellar-contracts"

[workspace.dependencies.worker]
path = "workers/worker"

[profile.dev]
opt-level = 0
incremental = true
codegen-units = 256

[profile.dev.package."*"]
opt-level = 2

[profile.test]
opt-level = 1
incremental = true

[profile.release]
opt-level = "z"
overflow-checks = true
debug = 0
strip = "symbols"
debug-assertions = false
panic = "abort"
codegen-units = 1
lto = true

[profile.release-with-logs]
inherits = "release"
debug-assertions = true
